name: financial_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2  # Usando la versión exacta que aparece como disponible
  path: 1.9.1      # Versión exacta que muestra como disponible
  cupertino_icons: ^1.0.8
  intl: ^0.18.1  # Agrega esta línea
  fl_chart: ^0.64.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.7
  showcaseview: ^2.0.0  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  meta: ^1.17.0
  vector_math: ^2.2.0
  material_color_utilities: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/play_store_512.png

flutter_launcher_icons:
  android: "launcher_icon"  # Nombre personalizado (opcional)
  ios: true
  web:
    generate: true
    image_path: "assets/icons/play_store_512.png"  # Opcional (ícono específico para web)
  image_path: "assets/icons/play_store_512.png"
  adaptive_icon_background: "#42a5f5"  # Fondo para ícono adaptable (Android)
